[package]
name = "teo"
version = "0.0.57-alpha.2"
edition = "2021"
description = "Next-generation web framework for Rust, Node.js and Python."
license = "Apache-2.0"
build = "build.rs"
homepage = "https://teocloud.io"
documentation = "https://teocloud.io/docs"
repository = "https://github.com/teocloud/teo"

[dependencies]
actix-web = "4.3.1"
actix-http = "3.3.1"
actix-web-lab = "0.19.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
chrono = { version = "0.4.24", features = ["serde"] }
random-string = "1.0"
jsonwebtoken = "8.2.0"
futures = "0.3.27"
futures-util = "0.3.27"
regex = "1.5.5"
tokio = { version = "1.0", features = ["macros"] }
async-trait = "0.1.66"
inflector-plus = "0.11.7"
url = "2.3.1"
bcrypt = "0.15.0"
uuid = { version = "1.1.1", features = ["v4", "fast-rng"] }
cuid2 = "0.1.0"
cuid = "=1.2.0"
mongodb = { version = "2.4.0", optional = true }
bson = { version = "2.5.0", features = ["chrono-0_4", "serde_with"], optional = true }
bigdecimal = "0.3.1"
async-recursion = "1.0.2"
colored = "2.0.0"
num-integer = "0.1.45"
pad = "0.1.6"
maplit = "1.0.2"
key-path = "0.1.11"
once_cell = "1.15"
indexmap = "2.0.0"
itertools = "0.11.0"
array_tool = "1.0.3"
pest = "2.7.1"
pest_derive = "2.7.1"
snailquote = "0.3.1"
clap = { version = "4.1.4", features = ["derive"] }
path-absolutize = "3.0.14"
dotenvy = "0.15.6"
toml_edit = "0.19.3"
quaint-forked = { version = "0.1.3-alpha.5", features = [ "all" ], optional = true }
whoami = { version = "1.3.0" }
to-mut = "0.1.0"
to-mut-proc-macro = "0.1.0"
rand = "0.8.4"
askama = "0.12.0"
pathdiff = "0.2.1"

[dev-dependencies]
serial_test = "2.0.0"
test-helpers = "0.2.3"
reqwest = { version = "0.11", features = ["json", "blocking"] }

[build-dependencies]
rustc_version = "0.4.0"

[features]
default = ["data-source-mongodb", "data-source-mysql", "data-source-postgres", "data-source-sqlite", "data-source-mssql"]
data-source-mongodb = ["mongodb", "bson"]
data-source-mysql = ["quaint-forked"]
data-source-postgres = ["quaint-forked"]
data-source-sqlite = ["quaint-forked"]
data-source-mssql = ["quaint-forked"]
