[package]
name = "teo"
version = "0.0.1"
edition = "2021"
description = "Backend Framework, Redefined"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
