[package]
name = "teo-derive"
version = "0.4.0-alpha.0"
edition = "2024"
rust-version = "1.88"
description = "High performance Rust ORM."
license = "MIT"

[lib]
name = "teo_derive"
proc-macro = true

[dependencies]
syn = { version = "2.0.104", features = ["full", "extra-traits"] }
quote = { version = "1.0.40" }
proc-macro2 = { version = "1.0.95" }

# [dev-dependencies]
# teo = { version = "0.0.1", path = "../teo" }
